spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD}
